=head1 NAME

heri-split - splits the dataset into training and testing sets

=head1 SYNOPSIS

B<heri-split> [OPTIONS] I<dataset1> [I<dataset2>...]

=head1 DESCRIPTION

B<heri-split> splits the dataset into several training and testing
sets as it is required for N-fold cross-validation. Dataset contains
one object per line as in svmlight format. By default
stratified sampling is used. That is, all folds contain
the same number of objects for each label.
If option B<-c> is specified, testI<N>.txt and trainI<N>.txt files
(also in svmlight format) are created, where I<N> is the number of fold.
Also testing_fold.txt file is created, where for each object (one per line)
its testing fold number is specified.

=head1 OPTIONS

=over 6

=item B<-h, --help>

Display help information.

=item B<-c, --folds> I<count>

Set the number of folds. This is a mandatory option.

=item B<-d, --output-dir> I<dir>

Set the output directory. This is a mandatory option.

=item B<-r,--random>

Use random sampling instead of stratified one.

=item B<-s, --seed> I<seed>

Set the seed value for pseudorandom generator.

=back

=head1 HOME

L<http://github.com/cheusov/herisvm>

=head1 SEE ALSO

L<heri-eval(1)>
L<heri-stat(1)>
